export const LOCATION_OPTIONS = [
  { label: "Afghanistan - Kabul", query: "Kabul,AF" },
  { label: "Albania - Tirana", query: "Tirana,AL" },
  { label: "Algeria - Algiers", query: "Algiers,DZ" },
  { label: "Andorra - Andorra la Vella", query: "Andorra la Vella,AD" },
  { label: "Angola - Luanda", query: "Luanda,AO" },
  { label: "Antigua and Barbuda - Saint John's", query: "Saint John's,AG" },
  { label: "Argentina - Buenos Aires", query: "Buenos Aires,AR" },
  { label: "Armenia - Yerevan", query: "Yerevan,AM" },
  { label: "Australia - Canberra", query: "Canberra,AU" },
  { label: "Austria - Vienna", query: "Vienna,AT" },
  { label: "Azerbaijan - Baku", query: "Baku,AZ" },
  { label: "Bahamas - Nassau", query: "Nassau,BS" },
  { label: "Bahrain - Manama", query: "Manama,BH" },
  { label: "Bangladesh - Dhaka", query: "Dhaka,BD" },
  { label: "Barbados - Bridgetown", query: "Bridgetown,BB" },
  { label: "Belarus - Minsk", query: "Minsk,BY" },
  { label: "Belgium - Brussels", query: "Brussels,BE" },
  { label: "Belize - Belmopan", query: "Belmopan,BZ" },
  { label: "Benin - Porto-Novo", query: "Porto-Novo,BJ" },
  { label: "Bhutan - Thimphu", query: "Thimphu,BT" },
  { label: "Bolivia - La Paz", query: "La Paz,BO" },
  { label: "Bosnia and Herzegovina - Sarajevo", query: "Sarajevo,BA" },
  { label: "Botswana - Gaborone", query: "Gaborone,BW" },
  { label: "Brazil - Brasilia", query: "Brasilia,BR" },
  { label: "Brunei - Bandar Seri Begawan", query: "Bandar Seri Begawan,BN" },
  { label: "Bulgaria - Sofia", query: "Sofia,BG" },
  { label: "Burkina Faso - Ouagadougou", query: "Ouagadougou,BF" },
  { label: "Burundi - Gitega", query: "Gitega,BI" },
  { label: "Cabo Verde - Praia", query: "Praia,CV" },
  { label: "Cambodia - Phnom Penh", query: "Phnom Penh,KH" },
  { label: "Cameroon - Yaounde", query: "Yaounde,CM" },
  { label: "Canada - Ottawa", query: "Ottawa,CA" },
  { label: "Central African Republic - Bangui", query: "Bangui,CF" },
  { label: "Chad - N'Djamena", query: "N'Djamena,TD" },
  { label: "Chile - Santiago", query: "Santiago,CL" },
  { label: "China - Beijing", query: "Beijing,CN" },
  { label: "Colombia - Bogota", query: "Bogota,CO" },
  { label: "Comoros - Moroni", query: "Moroni,KM" },
  { label: "Congo - Brazzaville", query: "Brazzaville,CG" },
  { label: "Costa Rica - San Jose", query: "San Jose,CR" },
  { label: "Croatia - Zagreb", query: "Zagreb,HR" },
  { label: "Cuba - Havana", query: "Havana,CU" },
  { label: "Cyprus - Nicosia", query: "Nicosia,CY" },
  { label: "Czechia - Prague", query: "Prague,CZ" },
  { label: "Democratic Republic of the Congo - Kinshasa", query: "Kinshasa,CD" },
  { label: "Denmark - Copenhagen", query: "Copenhagen,DK" },
  { label: "Djibouti - Djibouti", query: "Djibouti,DJ" },
  { label: "Dominica - Roseau", query: "Roseau,DM" },
  { label: "Dominican Republic - Santo Domingo", query: "Santo Domingo,DO" },
  { label: "Ecuador - Quito", query: "Quito,EC" },
  { label: "Egypt - Cairo", query: "Cairo,EG" },
  { label: "El Salvador - San Salvador", query: "San Salvador,SV" },
  { label: "Equatorial Guinea - Malabo", query: "Malabo,GQ" },
  { label: "Eritrea - Asmara", query: "Asmara,ER" },
  { label: "Estonia - Tallinn", query: "Tallinn,EE" },
  { label: "Eswatini - Mbabane", query: "Mbabane,SZ" },
  { label: "Ethiopia - Addis Ababa", query: "Addis Ababa,ET" },
  { label: "Fiji - Suva", query: "Suva,FJ" },
  { label: "Finland - Helsinki", query: "Helsinki,FI" },
  { label: "France - Paris", query: "Paris,FR" },
  { label: "Gabon - Libreville", query: "Libreville,GA" },
  { label: "Gambia - Banjul", query: "Banjul,GM" },
  { label: "Georgia - Tbilisi", query: "Tbilisi,GE" },
  { label: "Germany - Berlin", query: "Berlin,DE" },
  { label: "Ghana - Accra", query: "Accra,GH" },
  { label: "Greece - Athens", query: "Athens,GR" },
  { label: "Grenada - Saint George's", query: "Saint George's,GD" },
  { label: "Guatemala - Guatemala City", query: "Guatemala City,GT" },
  { label: "Guinea - Conakry", query: "Conakry,GN" },
  { label: "Guinea-Bissau - Bissau", query: "Bissau,GW" },
  { label: "Guyana - Georgetown", query: "Georgetown,GY" },
  { label: "Haiti - Port-au-Prince", query: "Port-au-Prince,HT" },
  { label: "Honduras - Tegucigalpa", query: "Tegucigalpa,HN" },
  { label: "Hungary - Budapest", query: "Budapest,HU" },
  { label: "Iceland - Reykjavik", query: "Reykjavik,IS" },
  { label: "India - New Delhi", query: "New Delhi,IN" },
  { label: "Indonesia - Jakarta", query: "Jakarta,ID" },
  { label: "Iran - Tehran", query: "Tehran,IR" },
  { label: "Iraq - Baghdad", query: "Baghdad,IQ" },
  { label: "Ireland - Dublin", query: "Dublin,IE" },
  { label: "Israel - Jerusalem", query: "Jerusalem,IL" },
  { label: "Italy - Rome", query: "Rome,IT" },
  { label: "Jamaica - Kingston", query: "Kingston,JM" },
  { label: "Japan - Tokyo", query: "Tokyo,JP" },
  { label: "Jordan - Amman", query: "Amman,JO" },
  { label: "Kazakhstan - Astana", query: "Astana,KZ" },
  { label: "Kenya - Nairobi", query: "Nairobi,KE" },
  { label: "Kiribati - Tarawa", query: "Tarawa,KI" },
  { label: "Kuwait - Kuwait City", query: "Kuwait City,KW" },
  { label: "Kyrgyzstan - Bishkek", query: "Bishkek,KG" },
  { label: "Laos - Vientiane", query: "Vientiane,LA" },
  { label: "Latvia - Riga", query: "Riga,LV" },
  { label: "Lebanon - Beirut", query: "Beirut,LB" },
  { label: "Lesotho - Maseru", query: "Maseru,LS" },
  { label: "Liberia - Monrovia", query: "Monrovia,LR" },
  { label: "Libya - Tripoli", query: "Tripoli,LY" },
  { label: "Liechtenstein - Vaduz", query: "Vaduz,LI" },
  { label: "Lithuania - Vilnius", query: "Vilnius,LT" },
  { label: "Luxembourg - Luxembourg", query: "Luxembourg,LU" },
  { label: "Madagascar - Antananarivo", query: "Antananarivo,MG" },
  { label: "Malawi - Lilongwe", query: "Lilongwe,MW" },
  { label: "Malaysia - Kuala Lumpur", query: "Kuala Lumpur,MY" },
  { label: "Maldives - Male", query: "Male,MV" },
  { label: "Mali - Bamako", query: "Bamako,ML" },
  { label: "Malta - Valletta", query: "Valletta,MT" },
  { label: "Marshall Islands - Majuro", query: "Majuro,MH" },
  { label: "Mauritania - Nouakchott", query: "Nouakchott,MR" },
  { label: "Mauritius - Port Louis", query: "Port Louis,MU" },
  { label: "Mexico - Mexico City", query: "Mexico City,MX" },
  { label: "Micronesia - Palikir", query: "Palikir,FM" },
  { label: "Moldova - Chisinau", query: "Chisinau,MD" },
  { label: "Monaco - Monaco", query: "Monaco,MC" },
  { label: "Mongolia - Ulaanbaatar", query: "Ulaanbaatar,MN" },
  { label: "Montenegro - Podgorica", query: "Podgorica,ME" },
  { label: "Morocco - Rabat", query: "Rabat,MA" },
  { label: "Mozambique - Maputo", query: "Maputo,MZ" },
  { label: "Myanmar - Naypyidaw", query: "Naypyidaw,MM" },
  { label: "Namibia - Windhoek", query: "Windhoek,NA" },
  { label: "Nauru - Yaren", query: "Yaren,NR" },
  { label: "Nepal - Kathmandu", query: "Kathmandu,NP" },
  { label: "Netherlands - Amsterdam", query: "Amsterdam,NL" },
  { label: "New Zealand - Wellington", query: "Wellington,NZ" },
  { label: "Nicaragua - Managua", query: "Managua,NI" },
  { label: "Niger - Niamey", query: "Niamey,NE" },
  { label: "Nigeria - Lagos", query: "Lagos,NG" },
  { label: "North Korea - Pyongyang", query: "Pyongyang,KP" },
  { label: "North Macedonia - Skopje", query: "Skopje,MK" },
  { label: "Norway - Oslo", query: "Oslo,NO" },
  { label: "Oman - Muscat", query: "Muscat,OM" },
  { label: "Pakistan - Islamabad", query: "Islamabad,PK" },
  { label: "Palau - Ngerulmud", query: "Ngerulmud,PW" },
  { label: "Panama - Panama City", query: "Panama City,PA" },
  { label: "Papua New Guinea - Port Moresby", query: "Port Moresby,PG" },
  { label: "Paraguay - Asuncion", query: "Asuncion,PY" },
  { label: "Peru - Lima", query: "Lima,PE" },
  { label: "Philippines - Manila", query: "Manila,PH" },
  { label: "Poland - Warsaw", query: "Warsaw,PL" },
  { label: "Portugal - Lisbon", query: "Lisbon,PT" },
  { label: "Qatar - Doha", query: "Doha,QA" },
  { label: "Romania - Bucharest", query: "Bucharest,RO" },
  { label: "Russia - Moscow", query: "Moscow,RU" },
  { label: "Rwanda - Kigali", query: "Kigali,RW" },
  { label: "Saint Kitts and Nevis - Basseterre", query: "Basseterre,KN" },
  { label: "Saint Lucia - Castries", query: "Castries,LC" },
  { label: "Saint Vincent and the Grenadines - Kingstown", query: "Kingstown,VC" },
  { label: "Samoa - Apia", query: "Apia,WS" },
  { label: "San Marino - San Marino", query: "San Marino,SM" },
  { label: "Sao Tome and Principe - Sao Tome", query: "Sao Tome,ST" },
  { label: "Saudi Arabia - Riyadh", query: "Riyadh,SA" },
  { label: "Senegal - Dakar", query: "Dakar,SN" },
  { label: "Serbia - Belgrade", query: "Belgrade,RS" },
  { label: "Seychelles - Victoria", query: "Victoria,SC" },
  { label: "Sierra Leone - Freetown", query: "Freetown,SL" },
  { label: "Singapore - Singapore", query: "Singapore,SG" },
  { label: "Slovakia - Bratislava", query: "Bratislava,SK" },
  { label: "Slovenia - Ljubljana", query: "Ljubljana,SI" },
  { label: "Solomon Islands - Honiara", query: "Honiara,SB" },
  { label: "Somalia - Mogadishu", query: "Mogadishu,SO" },
  { label: "South Africa - Pretoria", query: "Pretoria,ZA" },
  { label: "South Korea - Seoul", query: "Seoul,KR" },
  { label: "South Sudan - Juba", query: "Juba,SS" },
  { label: "Spain - Madrid", query: "Madrid,ES" },
  { label: "Sri Lanka - Colombo", query: "Colombo,LK" },
  { label: "Sudan - Khartoum", query: "Khartoum,SD" },
  { label: "Suriname - Paramaribo", query: "Paramaribo,SR" },
  { label: "Sweden - Stockholm", query: "Stockholm,SE" },
  { label: "Switzerland - Bern", query: "Bern,CH" },
  { label: "Syria - Damascus", query: "Damascus,SY" },
  { label: "Taiwan - Taipei", query: "Taipei,TW" },
  { label: "Tajikistan - Dushanbe", query: "Dushanbe,TJ" },
  { label: "Tanzania - Dodoma", query: "Dodoma,TZ" },
  { label: "Thailand - Bangkok", query: "Bangkok,TH" },
  { label: "Timor-Leste - Dili", query: "Dili,TL" },
  { label: "Togo - Lome", query: "Lome,TG" },
  { label: "Tonga - Nuku'alofa", query: "Nuku'alofa,TO" },
  { label: "Trinidad and Tobago - Port of Spain", query: "Port of Spain,TT" },
  { label: "Tunisia - Tunis", query: "Tunis,TN" },
  { label: "Turkey - Ankara", query: "Ankara,TR" },
  { label: "Turkmenistan - Ashgabat", query: "Ashgabat,TM" },
  { label: "Tuvalu - Funafuti", query: "Funafuti,TV" },
  { label: "Uganda - Kampala", query: "Kampala,UG" },
  { label: "Ukraine - Kyiv", query: "Kyiv,UA" },
  { label: "United Arab Emirates - Abu Dhabi", query: "Abu Dhabi,AE" },
  { label: "United Kingdom - London", query: "London,GB" },
  { label: "United States - Washington", query: "Washington,US" },
  { label: "Uruguay - Montevideo", query: "Montevideo,UY" },
  { label: "Uzbekistan - Tashkent", query: "Tashkent,UZ" },
  { label: "Vanuatu - Port Vila", query: "Port Vila,VU" },
  { label: "Vatican City - Vatican City", query: "Vatican City,VA" },
  { label: "Venezuela - Caracas", query: "Caracas,VE" },
  { label: "Vietnam - Hanoi", query: "Hanoi,VN" },
  { label: "Yemen - Sanaa", query: "Sanaa,YE" },
  { label: "Zambia - Lusaka", query: "Lusaka,ZM" },
  { label: "Zimbabwe - Harare", query: "Harare,ZW" },
];
